name: Create and Upload Custom Zip

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Folder
        run: mkdir result

      - name: Create zip file
        run: zip -r result/wc-donation-platform.zip . -x "node_modules/*" ".github/*" "package-lock.json" "pnpm-lock.yaml" ".idea/" "result" ".git" ".gitignore"

      - name: Deploy via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTPS_SERVER }}
          username: ${{ secrets.FTPS_USERNAME }}
          password: ${{ secrets.FTPS_PASSWORD }}
          protocol: ftps
          local-dir: ./result/
          remote-dir: /

      - name: Cleanup zip file
        run: rm result -r
