name: Create and Upload Custom Zip

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create zip file
        run: zip -r wc-donation-platform.zip .

      - name: Deploy via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTPS_SERVER }}
          username: ${{ secrets.FTPS_USERNAME }}
          password: ${{ secrets.FTPS_PASSWORD }}
          protocol: ftps
          local-dir: wc-donation-platform.zip
          remote-dir: /

      - name: Cleanup zip file
        run: rm wc-donation-platform.zip
