name: Create and Upload Custom Zip

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Folder
        run: mkdir -p ./result/wc-donation-platform

      - name: Copy Files
        run: rsync -av --prune-empty-dirs --exclude 'node_modules/*' --exclude 'wc-donation-platform/*' --exclude '.github/*' --exclude 'package-lock.json' --exclude 'pnpm-lock.yaml' --exclude '.idea/*' --exclude 'result/*' --exclude '.git/*' --exclude '.gitignore' ./ result/wc-donation-platform

      - name: Create zip file
        run: cd ./result && zip -r wc-donation-platform.1.3b.zip ./wc-donation-platform

      - name: Cleanup tmp files
        run: rm ./result/wc-donation-platform -r

      - name: Deploy via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTPS_SERVER }}
          username: ${{ secrets.FTPS_USERNAME }}
          password: ${{ secrets.FTPS_PASSWORD }}
          protocol: ftps
          local-dir: ./result/

      - name: Cleanup zip file
        run: rm result -r
