name: Create and Upload Custom Zip

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload zip file
        uses: actions/upload-artifact@v4
        with:
          retention-days: 90
          name: wc-donation-platform
          path: .
